### ISSUE TITLE
issues with oobabot_plugin

### ISSUE THREAD

**Issue by TheCyberViking** [chrisrude/oobabot-plugin#36]
I have installed web-ui using the one-click installer in which it loads the conda environment separately as files in a folder called installed_files. 

I tried the following:
- installed oobabot_plugin via pip
- ran the oobabot_plugin install in the main directory of the web-UI
- tried to reload and got an error of missing scripts, so copied all the content of oobabot into the created directory and the full contents of oobabot_plugin to try to get around the missing files.

Now im still getting the following issues:

2023-09-09 02:26:33 INFO: Loading the extension "oobabot_plugin"...
2023-09-09 02:26:33 ERROR: Failed to load the extension "oobabot_plugin".
Traceback (most recent call last):
  File "H:\Text_generation_character_chat\text-generation-webui\modules\extensions.py", line 35, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'extensions.oobabot_plugin.script'
2023-09-09 02:26:33 INFO: Loading the extension "gallery"...
Running on local URL:  http://0.0.0.0:7860

Although I have confirmed oobabot_plugin is installed it's not recognised.

any ideas?

**Comment by TheCyberViking** [comment]
Issue Solved, Using the one-click install here is how you install. 

1. Copy contents of oobabot and oobabot_plugin to your extensions folder in a folder called oobabot
2. go back to the main overall directory where you have start_windows.bat and run cmd_windows.bat (this will open cmd inside the portable conda environment)
3. run in that cmd python -m pip install oobabot-plugin
4. set the flags in CMD_FLAGS.txt as --extensions oobabot
5. Run start_windows.bat and when the web-ui loads oobabot will be there as a tab

**Comment by TheCyberViking** [comment]
New Issue related possibly. When following my steps above the plugin loads and all is accessible, although I noticed this issue appeared when I tried to load a model. When I remove the plugin and restart the server, the model loads in fine, error only appears to happen when the extension is loaded and then model is loaded that it spits out the following error.


Traceback (most recent call last):

File “H:\Text_generation_character_chat\text-generation-webui\modules\ui_model_menu.py”, line 196, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File “H:\Text_generation_character_chat\text-generation-webui\modules\[models.py](http://models.py/)”, line 79, in load_model

output = load_func_map[loader](model_name)
File “H:\Text_generation_character_chat\text-generation-webui\modules\[models.py](http://models.py/)”, line 320, in AutoGPTQ_loader

return modules.AutoGPTQ_loader.load_quantized(model_name)
File “H:\Text_generation_character_chat\text-generation-webui\modules\AutoGPTQ_loader.py”, line 57, in load_quantized

model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
File “H:\Text_generation_character_chat\installer_files\env\lib\site-packages\auto_gptq\modeling\[auto.py](http://auto.py/)”, line 108, in from_quantized

return quant_func(
File “H:\Text_generation_character_chat\installer_files\env\lib\site-packages\auto_gptq\modeling_base.py”, line 917, in from_quantized

cls.fused_mlp_module_type.inject_to_model(
File “H:\Text_generation_character_chat\installer_files\env\lib\site-packages\auto_gptq\nn_modules\fused_llama_mlp.py”, line 280, in inject_to_model

logger.warning(f"skip module injection for {cls.__name__} not support integrate without triton yet.")
File “H:\Text_generation_character_chat\installer_files\env\lib\logging_init_.py”, line 1489, in warning

self._log(WARNING, msg, args, **kwargs)
File “H:\Text_generation_character_chat\installer_files\env\lib\logging_init_.py”, line 1624, in _log

self.handle(record)
File “H:\Text_generation_character_chat\installer_files\env\lib\logging_init_.py”, line 1634, in handle

self.callHandlers(record)
File “H:\Text_generation_character_chat\installer_files\env\lib\logging_init_.py”, line 1704, in callHandlers

lastResort.handle(record)
File “H:\Text_generation_character_chat\installer_files\env\lib\logging_init_.py”, line 968, in handle

self.emit(record)
File “H:\Text_generation_character_chat\text-generation-webui\modules\logging_colors.py”, line 74, in new

args[0]._set_color(color)
AttributeError: ‘_StderrHandler’ object has no attribute ‘_set_color’
